library(raster)
library(data.table)
library(foreach)

source("Model/parameters.R")
source("Model/src/initialize.R")
source("Model/src/landscape.R")
source("Model/src/generate_grid.R")
source("Model/src/generate_agents.R")
source("Model/src/distribute_agents.R")
source("Model/src/birth.R")
source("Model/src/death.R")
source("Model/src/immigration.R")
source("Model/src/animate.R")
source("Model/src/cookie_cutting.R")
source("Model/src/disperse.R")
source("Model/src/run_model_step.R")
source("Model/src/clean_run.R")
source("R/sample_cells.R")
source("R/toroidal_clump.R")


# 0. Setup ----------------------------------------------------------------

# A new state can be generated by running the dynamic model with clean_run().
# This might take a while (especially if run locally).
# Alternatively, previously generated and exported states can be read in. 
# In this case section 0.1 can be skipped.

  ## 0.1 - Generate new state ####

sim_id <- 3

# Run dynamic model and get full state right after fragmentation
states_high <- clean_run(
  mod_par = mod_par,
  var_par = var_par,
  switch = switch,
  sim_id = sim_id,
  record_steps = "post_fragmentation",
  seed = seed
) 
post_frag_high <- states_high$post_fragmentation

# Export as RDS
saveRDS(post_frag_high, "data-raw/post_frag_high_state_1.rds")

  ## 0.2 - Read in previously exported states ####
post_frag_high <- readRDS("data-raw/post_frag_high_state_1.rds")


# Sampling ----------------------------------------------------------------


# 30 random habitat cells
low_sample_ran <- sample_cells(post_frag_low, method = "random", n_samples = 30)
high_sample_ran <- sample_cells(post_frag_high, method = "random", n_samples = 30)


# All habitat cells
low_sample_all <- sample_cells(post_frag_low, method = "all")
high_sample_all <- sample_cells(post_frag_high, method = "all")


# Every other cell (chessboard sampling)
low_sample_cb <- sample_cells(post_frag_low, method = "chessboard")
high_sample_cb <- sample_cells(post_frag_high, method = "chessboard")


# Export as CSVs
write.csv(low_sample_ran, "data-raw/post_frag_low_sample_ran.csv")
write.csv(low_sample_all, "data-raw/post_frag_low_sample_full.csv")
write.csv(low_sample_cb, "data-raw/post_frag_low_sample_cb.csv")

write.csv(high_sample_ran, "data-raw/post_frag_high_sample_ran.csv")
write.csv(high_sample_all, "data-raw/post_frag_high_sample_full.csv")
write.csv(high_sample_cb, "data-raw/post_frag_high_sample_cb.csv")

